VEHICLE_REGISTRATIONS = """
SELECT TOP 5 
VR_PERSON_ID AS life_id,
VR_PERMIT_ID AS permit_id,
VR_PERMIT_ISSUE_DATE AS issue_date,
VR_PERMIT_START_DATE AS start_date,
VR_PERMIT_END_DATE AS end_date,
VR_REGISTRANT_TYPE AS registrant_type,
VR_LICENSE_PLATE AS license_plate,
VR_LICENSE_PLATE_STATE AS license_plate_state,
VR_VEHICLE_COLOR AS color,
VR_VEHICLE_MAKE AS make,
VR_VEHICLE_MODEL AS model,
VR_COMMENTS AS comments
FROM VEHICLE_REGISTRATION (NOLOCK)
"""